apiDefinitions:
  validation_v1: ./openapi/validation_v1/openapi.yaml
  sign_v2: ./openapi/sign_v2/openapi.yaml
  sign_v3: ./openapi/sign_v3/openapi.yaml
lint:
  rules:
    no-unused-components: warn
    operation-2xx-response: error
referenceDocs:
  validation_v1:
    markdown:
      overview: ./docs/validation.md
      authentication: ./docs/authentication.md
      errors: ./docs/errors.md
      changelog: ./docs/changelog.md
  sign_v2:
    markdown:
      overview: ./docs/signing.md
      authentication: ./docs/authentication.md
      errors: ./docs/errors.md
      changelog: ./docs/changelog.md
  sign_v3:
    markdown:
      overview: ./docs/signing.md
      authentication: ./docs/authentication.md
      errors: ./docs/errors.md
      changelog: ./docs/changelog.md
